### ISSUE TITLE
mvn build error

### ISSUE THREAD

**Issue by chakravarthi-vl** [mangosystem/opengxt#10]
@mapplus 
 when i am building gt-process-spatialstatistics showing this error

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:17 min
[INFO] Finished at: 2019-07-09T17:40:55+05:30
[INFO] Final Memory: 13M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gt-process-spatialstatistics: Could not resolve dependencies for project org.geotools:gt-process-spatialstatistics:jar:21-SNAPSHOT: Failed to collect dependencies at org.geotools:gt-referencing:jar:21-SNAPSHOT: Failed to read artifact descriptor for org.geotools:gt-referencing:jar:21-SNAPSHOT: Could not transfer artifact org.geotools:gt-referencing:pom:21-SNAPSHOT from/to boundless (>https://repo.boundlessgeo.com/main/): Cannot access >https://repo.boundlessgeo.com/main/ with type default using the available connector factories: BasicRepositoryConnectorFactory: Cannot access >https://repo.boundlessgeo.com/main/ using the registered transporter factories: WagonTransporterFactory: java.util.NoSuchElementException
[ERROR] role: org.apache.maven.wagon.Wagon
[ERROR] roleHint: >https
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jinifor** [comment]
@chakravarthi-vl Delete the local mvn library folder and try again.
