### ISSUE TITLE
RasterSlope나 RasterAspect 분석 결과를 png로 요청 시 에러

### ISSUE THREAD

**Issue by kwunjaehyun** [mangosystem/opengxt#19]
안녕하세요. OpenGxt를 감사히 잘 사용하고 있습니다.

raster자료에 대해 분석결과가 필요하여 RasterSlope와 RasterAspect를 사용중인데,

결과를 png로 요청시 

<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://localhost:8080/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>An error occurred while encoding the results of the process
No suitable image writer for this output.</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

와 같은 에러가 발생합니다.

tiff나 jpg로 요청 할 때에는 정상 작동합니다.

혹 geoserver에 등록된 레이어에 따로 설정같은 걸 해주거나 원본에 따로 처리를 해야 할까요?

사용중인 geoserver는 2.16.2 버전입니다.

감사합니다.

**Comment by jinifor** [comment]
안녕하세요.

**RasterSlope**, **RasterAspect** 프로세스의 Output 타입은 image/tiff, application/arcgrid 입니다.
png, jpg와 같은 이미지 형식으로는 반환되지 않습니다.

이미지 파일 형태로(png, jpg 등) 래스터 파일을 받기 위해서는 앞서 사용한 프로세스의 결과 래스터를  **RasterToImage** 프로세스의 coverage(Input Raster) 파라미터로 체이닝 하면 image/png 타입으로 이미지를 추출할 수 있습니다.

**Comment by kwunjaehyun** [comment]
답변 감사드립니다.

데모에 WPS 요청 빌더에

![image](https://user-images.githubusercontent.com/49637263/82311041-233b7c80-9a00-11ea-882b-f55d3f831bf8.png)

와 같이 되있어서 가능한지 알았습니다.ㅎㅎ

RasterToImage 이용하여 처리토록 하겠습니다.

다시 한번 감사드립니다.
