### ISSUE TITLE
geoserver 2.7.6 version 호환

### ISSUE THREAD

**Issue by shinekill** [mangosystem/opengxt#20]
안녕하세요. 

geoserver 2.7.6 버전에 대응하는 jar 파일은 sourceforge.net에 올라가 있지 않은 것으로 확인했습니다.

혹시 gt-13.x branch에 있는 소스를 사용하면 2.7.6버전에서 사용 가능한지 여쭙고 싶습니다.

감사합니다.

**Comment by jinifor** [comment]
@shinekill 
안녕하세요. GeoSever 2.7.6 버전은 GeoTools 13.6을 사용하고 있습니다. ([GeoServer Release Schedule](https://github.com/geoserver/geoserver/wiki/Release-Schedule))

말씀하신 바와 같이 https://github.com/mangosystem/opengxt/tree/gt-13.x branch를 사용하시면 됩니다.

감사합니다.
